version: "3"
services:
  task-manager:
    build: ./docker
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: